services:
  react-autoparts-app:
    container_name: react_app
    build:
      context: ./
      dockerfile: Docker/react/Dockerfile
    restart: always
    networks:
      autoparts_network:
        ipv4_address: 192.168.32.10

networks:
  autoparts_network:
    external: true