services:
  react-autoparts-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-autoparts-app
    restart: always
    networks:
      - autoparts_network

networks:
  autoparts_network:
    external: true