services:
  react-autoparts-app:
    container_name: react_app
    build:
      context: ./
      dockerfile: Docker/react/Dockerfile
    restart: always
    volumes:
      - /home/gvaurdin/ReactWebAPIAutoparts:/usr/src
    ports:
      - "3000:80"
    networks:
      autoparts_network-react:
        ipv4_address: 192.168.32.10

networks:
  autoparts_network-react:
    name: autoparts_network-react
    driver: bridge